config/routes.rb
Rails.application.routes.draw do


  # mount Blazer::Engine, at: "blazer"
  namespace :admin do
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]
      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
        put 'users' => 'devise/registrations#update', :as => 'user_registration'
        patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard
    resources :users
    resources :settings, only: [:new, :create, :edit, :update]
    resources :personalities
    resources :services
    resources :experiences
    resources :educations
    resources :skills
    resources :blogs
    resources :categories
    resources :achivements
    resources :visits
    resources :contacts, only: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :categories do
    resources :blogs
  end

  resources :blogs
  resources :homes
  resources :services
  resources :achivements

  #Api
  namespace :api do
    namespace :v1 do
      resources :blogs, only: [:index, :show]
    end
  end

  namespace :demo do
    namespace :v1 do
      get 'signup' => 'demo_users#new', :as => :signup
      get 'logout' => 'sessions#destroy', :as => :logout
      get 'login' => 'sessions#new', :as => :login
      resources :sessions
      resources :demo_users

      resources :todos
      root "todos#index"
    end
  end
end

app/models/achivement.rb
class Achivement < ApplicationRecord
  before_save :update_slug

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end

  belongs_to :user
  has_many :skills, inverse_of: :achivement
  belongs_to :category
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :update_slug

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
  belongs_to :user
  belongs_to :category
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs
  belongs_to :user
  has_many :achivements
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :full_name, presence: true
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates :email, presence: true
  validates :phone, numericality: true
end

app/models/demo_user.rb
class DemoUser < ApplicationRecord
  has_many :todos

  #Association
  validates :password, presence: true
  attr_accessor :password
  before_save :prepare_password

  #Validation

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /(?=.*[A-Za-z._@])/, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  #Class Method
  def self.authenticate(login, pass)
    customer = find_by_username(login) || find_by_email(login)
    return customer if customer && customer.matching_password?(pass)
  end

  #Instance Method
  def matching_password?(pass)
    self.password_hashL == encrypt_password(pass)
  end

  private

    def prepare_password
      unless password.blank?
        self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
        self.password_hashL = encrypt_password(password)
      end
    end

    def encrypt_password(pass)
      Digest::SHA1.hexdigest([pass, password_salt].join)
    end
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/personality.rb
class Personality < ApplicationRecord
  belongs_to :user
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
end

app/models/setting.rb
class Setting < ApplicationRecord
  #Association
  has_many  :socials, inverse_of: :setting
  accepts_nested_attributes_for :socials, :reject_if => :all_blank, :allow_destroy => true

  #Class Method
  def self.site_name
    Setting.first.try(:site_name)
  end

  def self.post_per_page
    Setting.first.try(:post_per_page)
  end

  def self.tag_visibility?
    Setting.first.try(:tag_visibility)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :achivement, optional: true
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :setting
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :demo_user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :vip, :admin, :staff]
  after_initialize :set_default_role, :if => :new_record?
  after_initialize :set_role_vip, :if => :new_record?

  has_many :personalities
  has_many :services
  has_many :experiences
  has_many :educations
  has_many :skills
  has_many :blogs
  has_many :categories
  has_many :achivements

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def set_role_vip
    self.role ||= :vip
  end


  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # validates :username, presence: true, uniqueness: true
  # validates :address, presence: true
  # validates :phone, presence: true, numericality: true
  # validates :image, presence: true
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :home, optional: true
  belongs_to :blog, optional: true
end

app/controllers/admin/visits_controller.rb
class Admin::VisitsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_administrator
  before_action :admin_only, only:[:destroy]

  def index
    @search = Visit.ransack(params[:search])
    @visitors = @search.result.order(id: :desc)
  end

  def show

  end

  private
    def admin_only
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, :notice => "Access denied."
        end
      end
    end

    def set_administrator
      @admin = User.where({role: "admin"})
    end

    def set_activity
      @visitor = Visit.find(params[:id])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/visits/index.html.erb
<%=render "shared/header-report"%>
<div class="c-toolbar u-mb-medium">
  <div class="col-xl-3 col-sm-3 col-md-3 c-toolbar__state">
    <h4 class="c-toolbar__state-number">Unknown</h4>
    <span class="c-toolbar__state-title">0</span>
  </div>
  <div class="col-xl-3 col-sm-3 col-md-3 c-toolbar__state">
    <h4 class="c-toolbar__state-number">Unknown</h4>
    <span class="c-toolbar__state-title">0</span>
  </div>
  <div class="col-xl-3 col-sm-3 col-md-3 c-toolbar__state">
    <h4 class="c-toolbar__state-number">13%</h4>
    <span class="c-toolbar__state-title">Favorite</span>
  </div>
  <div class="col-xl-3 col-sm-3 col-md-3 c-toolbar__state">
    <h4 class="c-toolbar__state-number">5%</h4>
    <span class="c-toolbar__state-title">New Registration</span>
  </div>

</div>
<br>
<div class="container-fluid">
  <div class="row u-mb-large">
    <div class="col-lg-3 col-xl-3 order-lg-2">
      <div class="c-search-form c-search-form--dark">
          <%= search_form_for([:admin, @search]) do |f|%>
            <h3 class="c-search-form__label" style="text-align:center;margin-bottom:20px;font-size:16px;">Search</h3>
            <%= link_to 'Clear Search', request.path, class: "c-btn c-btn--warning c-btn--fullwidth"%>
              <div class="c-search-form__section">
                <div class="c-field has-icon-left">
                  <small class="c-field__message">Enter IP</small>
                    <%=f.text_field :ip_cont, class: "c-input", :placeholder => "Search.."%>
                </div>
              </div>
              <div class="c-search-form__section">
                <div class="c-field has-icon-left">
                  <small class="c-field__message">Enter Country</small>
                    <%=f.text_field :country_cont, class: "c-input", :placeholder => "Search.."%>
                </div>
              </div>

              <div class="c-search-form__section">
                <div class="c-field has-icon-left">
                  <small class="c-field__message">Enter Os</small>
                    <%=f.text_field :os_cont, class: "c-input", :placeholder => "Search.."%>
                </div>
              </div>

              <%= f.submit 'Search', class: "c-btn c-btn--info c-btn--fullwidth"%>
              <br><br>
          <%end%>
        </div>
      </div>
      <div class="col-lg-9 col-xl-9 order-lg-1">
          <table class="c-table" id="datatable">
            <caption class="c-table__title">
              <div class="panhara-toolbar">
                <h4 class="c-toolbar__title has-divider"><span class="u-text-bold"> Activity Table</span></h4>
                <span class="c-toolbar__meta u-mr-auto">21 People match your criteria</span>
                <%=link_to "Back", admin_dashboard_path, :class=>"c-btn c-btn--blue u-hidden-down@mobile"%>
              </div>
            </caption>
              <thead class="c-table__head c-table__head--slim">
                  <tr class="c-table__row">
                      <th class="c-table__cell c-table__cell--head no-sort">IP Address</th>
                      <th class="c-table__cell c-table__cell--head no-sort">Agent</th>
                      <th class="c-table__cell c-table__cell--head no-sort">Browser</th>
                      <th class="c-table__cell c-table__cell--head no-sort">OS</th>
                      <th class="c-table__cell c-table__cell--head no-sort">Country</th>
                      <th class="c-table__cell c-table__cell--head no-sort">Actions</th>
                  </tr>
              </thead>

              <tbody>
                <%@visitors.each do |visitor|%>
                  <tr class="c-table__row">
                      <td class="c-table__cell"><%=visitor.ip%></td>
                      <td class="c-table__cell"><%=visitor.user_agent.truncate(15)%></td>
                      <td class="c-table__cell"><%=visitor.browser%></td>
                      <td class="c-table__cell"><%=visitor.os%></td>
                      <td class="c-table__cell"><%=visitor.country%></td>
                      <td class="c-table__cell">
                        <div class="c-dropdown dropdown">
                            <button class="c-btn c-btn--secondary has-dropdown dropdown-toggle" id="dropdownMenuButton10" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                            <div class="c-dropdown__menu dropdown-menu" aria-labelledby="dropdownMenuButton10">
                                <%=link_to "View", admin_visit_path(visitor), :class=>"c-dropdown__item dropdown-item"%>

                            </div>
                        </div>
                      </td>
                  </tr>
                <%end%>
              </tbody>
          </table>
      </div>
  </div>
</div><!-- // .container -->

app/views/admin/visits/show.html.erb
<%=render "shared/header-report"%>
<div class="c-toolbar u-justify-center u-mb-small">
    <div class="col-12 col-lg-10 col-xl-8">
        <div class="row">
            <div class="col-6 col-md-3 c-toolbar__state">
                <h4 class="c-toolbar__state-number">50</h4>
                <span class="c-toolbar__state-title">Registrated</span>
            </div>
            <div class="col-6 col-md-3 c-toolbar__state">
                <h4 class="c-toolbar__state-number">54%</h4>
                <span class="c-toolbar__state-title">Course Rate</span>
            </div>
            <div class="col-6 col-md-3 c-toolbar__state">
                <h4 class="c-toolbar__state-number">13%</h4>
                <span class="c-toolbar__state-title">Favorite</span>
            </div>
            <div class="col-6 col-md-3 c-toolbar__state">
                <h4 class="c-toolbar__state-number">5</h4>
                <span class="c-toolbar__state-title">New Registration</span>
            </div>
        </div><!-- // .row -->
    </div><!-- // -->
</div><!-- // .c-toolbar -->

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-xl-6">
      <div class="c-card u-p-medium u-text-small u-mb-small">
        <h6 class="u-text-bold">General Info</h6>

        <dl class="u-flex u-pv-small u-border-bottom">
          <dt class="u-width-25">IP Address</dt>
          <dd><%=@visitor.ip%></dd>
        </dl>

        <dl class="u-flex u-pv-small u-border-bottom">
          <dt class="u-width-25">Agent</dt>
          <dd><%=@visitor.user_agent%></dd>
        </dl>

        <dl class="u-flex u-pv-small u-border-bottom">
          <dt class="u-width-25">Browser</dt>
          <dd><%=@visitor.browser%></dd>
        </dl>

        <dl class="u-flex u-pv-small u-border-bottom">
          <dt class="u-width-25">OS</dt>
          <dd><%=@visitor.os%></dd>
        </dl>

        <dl class="u-flex u-pv-small u-border-bottom">
          <dt class="u-width-25">Country</dt>
          <dd><%=@visitor.country%></dd>
        </dl>

        <dl class="u-flex u-pv-small">
          <span><%=link_to "Cancel", admin_activities_path,:class=>"c-btn c-btn--danger"%></span>
        </dl>
      </div>
    </div>

  </div>
</div>