config/routes.rb
Rails.application.routes.draw do


  # mount Blazer::Engine, at: "blazer"
  namespace :admin do
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]
      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
        put 'users' => 'devise/registrations#update', :as => 'user_registration'
        patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard
    resources :users
    resources :settings, only: [:new, :create, :edit, :update]
    resources :personalities
    resources :services
    resources :experiences
    resources :educations
    resources :skills
    resources :blogs
    resources :categories
    resources :achivements
    resources :visits
    resources :contacts, only: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :categories do
    resources :blogs
  end

  resources :blogs
  resources :homes
  resources :services
  resources :achivements

  #Api
  namespace :api do
    namespace :v1 do
      resources :blogs, only: [:index, :show]
    end
  end

  namespace :demo do
    namespace :v1 do
      get 'signup' => 'demo_users#new', :as => :signup
      get 'logout' => 'sessions#destroy', :as => :logout
      get 'login' => 'sessions#new', :as => :login
      resources :sessions
      resources :demo_users

      resources :todos
      root "todos#index"
    end
  end
end

app/models/achivement.rb
class Achivement < ApplicationRecord
  before_save :update_slug

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end

  belongs_to :user
  has_many :skills, inverse_of: :achivement
  belongs_to :category
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :update_slug

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
  belongs_to :user
  belongs_to :category
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs
  belongs_to :user
  has_many :achivements
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :full_name, presence: true
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates :email, presence: true
  validates :phone, numericality: true
end

app/models/demo_user.rb
class DemoUser < ApplicationRecord
  has_many :todos

  #Association
  validates :password, presence: true
  attr_accessor :password
  before_save :prepare_password

  #Validation

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /(?=.*[A-Za-z._@])/, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  #Class Method
  def self.authenticate(login, pass)
    customer = find_by_username(login) || find_by_email(login)
    return customer if customer && customer.matching_password?(pass)
  end

  #Instance Method
  def matching_password?(pass)
    self.password_hashL == encrypt_password(pass)
  end

  private

    def prepare_password
      unless password.blank?
        self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
        self.password_hashL = encrypt_password(password)
      end
    end

    def encrypt_password(pass)
      Digest::SHA1.hexdigest([pass, password_salt].join)
    end
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/personality.rb
class Personality < ApplicationRecord
  belongs_to :user
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
end

app/models/setting.rb
class Setting < ApplicationRecord
  #Association
  has_many  :socials, inverse_of: :setting
  accepts_nested_attributes_for :socials, :reject_if => :all_blank, :allow_destroy => true

  #Class Method
  def self.site_name
    Setting.first.try(:site_name)
  end

  def self.post_per_page
    Setting.first.try(:post_per_page)
  end

  def self.tag_visibility?
    Setting.first.try(:tag_visibility)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :achivement, optional: true
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :setting
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :demo_user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :vip, :admin, :staff]
  after_initialize :set_default_role, :if => :new_record?
  after_initialize :set_role_vip, :if => :new_record?

  has_many :personalities
  has_many :services
  has_many :experiences
  has_many :educations
  has_many :skills
  has_many :blogs
  has_many :categories
  has_many :achivements

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def set_role_vip
    self.role ||= :vip
  end


  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # validates :username, presence: true, uniqueness: true
  # validates :address, presence: true
  # validates :phone, presence: true, numericality: true
  # validates :image, presence: true
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :home, optional: true
  belongs_to :blog, optional: true
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*

var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://panhara-work.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/shared/_fucked.html.erb
<%=render "shared/left-side-bar"%>
<main class="o-page__content">
  <%=render "shared/header"%>
    <div class="c-toolbar u-justify-center u-mb-small">
        <div class="col-12 col-lg-10 col-xl-8">
            <div class="row">
                <div class="col-6 col-md-3 c-toolbar__state">
                    <h4 class="c-toolbar__state-number">50%</h4>
                    <span class="c-toolbar__state-title">Nothing</span>
                </div>
                <div class="col-6 col-md-3 c-toolbar__state">
                    <h4 class="c-toolbar__state-number">54%</h4>
                    <span class="c-toolbar__state-title">Availble Courses</span>
                </div>
                <div class="col-6 col-md-3 c-toolbar__state">
                    <h4 class="c-toolbar__state-number">13%</h4>
                    <span class="c-toolbar__state-title">Favorite</span>
                </div>
                <div class="col-6 col-md-3 c-toolbar__state">
                    <h4 class="c-toolbar__state-number">5%</h4>
                    <span class="c-toolbar__state-title">New Registration</span>
                </div>
            </div><!-- // .row -->
        </div><!-- // -->
    </div><!-- // .c-toolbar -->
    <div class="container-fluid">
      <div class="row u-mb-large">
          <div class="col-12">
              <table class="c-table" id="datatable">
                  <caption class="c-table__title">
                    <%if current_admin_user.admin?%>
                      <%=link_to "New Staff", new_admin_user_path, :class=>"c-btn c-btn--info"%>
                    <%end%>

                    <%= render "admin/application/search", route: admin_users_path%>
                  </caption>

                  <thead class="c-table__head c-table__head--slim">
                      <tr class="c-table__row">
                          <th class="c-table__cell c-table__cell--head no-sort">Username</th>
                          <th class="c-table__cell c-table__cell--head no-sort">Role</th>
                          <th class="c-table__cell c-table__cell--head no-sort">Phone</th>
                          <th class="c-table__cell c-table__cell--head no-sort">Created_At</th>
                          <th class="c-table__cell c-table__cell--head no-sort">Actions</th>
                      </tr>
                  </thead>

                  <tbody>
                    <%@users.each do |user|%>
                      <tr class="c-table__row" >
                          <td class="c-table__cell"><%=user.username%></td>
                          <td class="c-table__cell"><%=user.role%></td>
                          <td class="c-table__cell"><%=user.email%></td>
                          <td class="c-table__cell"><%=time_ago(user.created_at)%></td>
                          <td class="c-table__cell">
                            <!-- <a href="invoice.html" class="c-btn c-btn--info u-mr-xsmall">Manage</a> -->
                              <div class="c-dropdown dropdown">
                                  <button class="c-btn c-btn--secondary has-dropdown dropdown-toggle" id="dropdownMenuButton10" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                                  <div class="c-dropdown__menu dropdown-menu" aria-labelledby="dropdownMenuButton10">
                                      <%=link_to "View", admin_user_path(user), :class=>"c-dropdown__item dropdown-item"%>
                                      <%=link_to "Edit", edit_admin_user_path(user), :class=>"c-dropdown__item dropdown-item"%>
                                      <%=link_to "Delete", admin_user_path(user), method: :delete, data: {:confirm => "Are you sure ?"}, :class=>"c-dropdown__item dropdown-item"%>
                                  </div>
                              </div>
                          </td>
                      </tr>
                    <%end%>
                  </tbody>
              </table>
          </div>
      </div>
    </div><!-- // .container -->

</main><!-- // .o-page__content -->
<div class="blog-block">
 <div class="blog-image">
   <img class="img-responsive" src="<%=blog.image%>" alt="">
   <div class="blog-date">
    <span><%=blog.post_date%></span>
   </div>
 </div>
 <div class="blog-info">
   <div class="blog-meta">
     <p><span class="ti-user"></span> <a href="#"><%=blog.author%> </a></p>
     <p><span class="ti-folder"></span> <%=link_to blog.category.category_name,blog.category%></p>
   </div>

   <div class="blog-content">
     <%=link_to blog.title,blog%>
     <p><%=raw blog.description.truncate(150)%></p>
     <div class="blog-bottom clearfix">
       <div class="button-small">
         <%=link_to("Read More",blog)%>
       </div>
       <div class="social pull-right">
         <ul>
           <li><a href="#"><i class="fa fa-facebook"></i> </a></li>
           <li><a href="#"><i class="fa fa-twitter"></i></a></li>
           <li><a href="#"><i class="fa fa-linkedin"></i> </a></li>
         </ul>
       </div>
     </div>
   </div>
 </div>
</div>
 <div class="card radius shadowDepth1">
   <div class="card__image border-tlr-radius">
     <img src="<%=blog.image%>" alt="" class="border-tlr-radius">
   </div>
   <div class="card__content card__padding">
     <div class="card__share">
       <div class="card__social">
         <a href="#" class="shared-icon facebook"> <span class="fa fa-facebook"></span> </a>
         <a href="#" class="shared-icon twitter"> <span class="fa fa-twitter"></span> </a>
         <a href="#" class="shared-icon googleplus"> <span class="fa fa-googleplus"></span> </a>
       </div>
       <a href="#" id="share" class="share-toggle share-icon"></a>
     </div>

     <div class="card_meta">
        <%=link_to blog.category.category_name,blog.category%>
       <time><%=blog.post_date%></time>
     </div>

     <article class="card__article">
       <h2><%=link_to blog.title, blog%></h2>
       <p><%=raw blog.description.truncate(20)%></p>
     </article>
   </div>

   <div class="card__action">
     <div class="card_author">
       <img src="" alt="image">
       <div class="card__author-content">
         By <%= blog.author%>
       </div>
     </div>
   </div>

 </div>

app/views/shared/_header-report.html.erb
<header class="c-navbar">
    <a class="c-navbar__brand" href="#!">
        <img src="img/logo.png" alt="logo">
    </a>

   <!-- Navigation items that will be collapes and toggle in small viewports -->
    <nav class="c-nav collapse" id="main-nav">
        <ul class="c-nav__list">
            <li class="c-nav__item">
              <%=link_to "Dashboard", admin_dashboard_path, :class=> "c-nav__link is-active"%>
            </li>
            <li class="c-nav__item">
                <%=link_to "Administrator", admin_users_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Personality", admin_personalities_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Service", admin_services_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Experience", admin_experiences_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Education", admin_educations_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Skill", admin_skills_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Portfolio", admin_achivements_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Blog", admin_blogs_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Category", admin_categories_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
              <%=link_to "Activity", admin_visits_path, :class=>"c-nav__link" %>
            </li>

            <li class="c-nav__item">
                <div class="c-field c-field--inline has-icon-right u-hidden-up@tablet">
                    <span class="c-field__icon">
                        <i class="fa fa-search"></i>
                    </span>

                    <label class="u-hidden-visually" for="navbar-search-small">Seach</label>
                    <input class="c-input" id="navbar-search-small" type="text" placeholder="Search">
                </div>
            </li>
        </ul>
    </nav>
    <!-- // Navigation items  -->

    <div class="c-dropdown u-ml-auto dropdown">
        <a  class="c-avatar c-avatar--xsmall has-dropdown dropdown-toggle" href="#" id="dropdwonMenuAvatar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="c-avatar__img" src="<%=current_admin_user.image%>" alt="">
        </a>

        <div class="c-dropdown__menu dropdown-menu dropdown-menu-right" aria-labelledby="dropdwonMenuAvatar">
            <a class="c-dropdown__item dropdown-item" href="#">Edit Profile</a>
            <a class="c-dropdown__item dropdown-item" href="#">View Activity</a>
            <%=link_to "Manage User", admin_users_path, :class=>"c-dropdown__item dropdown-item" %>
            <%=link_to "Setting", new_admin_setting_path, :class=>"c-dropdown__item dropdown-item" %>
            <%=link_to "Logout", destroy_admin_user_session_path, method: :delete, :class=>"c-dropdown__item dropdown-item"%>
        </div>
    </div>

    <button class="c-nav-toggle" type="button" data-toggle="collapse" data-target="#main-nav">
        <span class="c-nav-toggle__bar"></span>
        <span class="c-nav-toggle__bar"></span>
        <span class="c-nav-toggle__bar"></span>
    </button><!-- // .c-nav-toggle -->
</header>

app/views/shared/_header.html.erb
<header class="c-navbar u-mb-medium">
    <button class="c-sidebar-toggle u-mr-small">
        <span class="c-sidebar-toggle__bar"></span>
        <span class="c-sidebar-toggle__bar"></span>
        <span class="c-sidebar-toggle__bar"></span>
    </button><!-- // .c-sidebar-toggle -->

      <%if current_admin_user.username == nil%>
        <h2 class="c-navbar__title u-mr-auto">
          Welcome Back <p id="demo"></p>
        </h2>
      <%else%>
        <h2 class="c-navbar__title u-mr-auto">
          Welcome <%=current_admin_user.username.capitalize%>
        </h2>
      <%end%>

    <div class="c-dropdown u-hidden-down@mobile">
        <a class="c-notification dropdown-toggle" href="#" id="dropdownMenuUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="c-notification__icon">
                <i class="fa fa-user-o"></i>
            </span>
            <span class="c-notification__number">3</span>
        </a>

        <div class="c-dropdown__menu c-dropdown__menu--large dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuUser">
            <a href="#" class="c-dropdown__item dropdown-item o-media">
                <span class="o-media__img u-mr-xsmall">
                    <span class="c-avatar c-avatar--xsmall">
                        <img class="c-avatar__img" src="<%=current_admin_user.image%>" alt="">
                    </span>
                </span>
                <div class="o-media__body">
                    <h6 class="u-mb-zero">Someone mentioned you</h6>
                    <p class="u-text-mute">You have recieved a mention on twitter, check it out!</p>
                </div>
            </a>
            <a href="#" class="c-dropdown__item dropdown-item o-media">
                <span class="o-media__img u-mr-xsmall">
                    <span class="c-avatar c-avatar--xsmall">
                        <img class="c-avatar__img" src="img/avatar3-72.jpg" alt="User's Profile Picture">
                    </span>
                </span>
                <div class="o-media__body">
                    <h6 class="u-mb-zero">Recieved a Payment</h6>
                    <p class="u-text-mute">You have recieved a mention on twitter, check it out!</p>
                </div>
            </a>
            <a href="#" class="c-dropdown__item dropdown-item o-media">
                <span class="o-media__img u-mr-xsmall">
                    <span class="c-avatar c-avatar--xsmall">
                        <img class="c-avatar__img" src="img/avatar4-72.jpg" alt="User's Profile Picture">
                    </span>
                </span>
                <div class="o-media__body">
                    <h6 class="u-mb-zero">You got a promotion</h6>
                    <p class="u-text-mute">You have recieved a mention on twitter, check it out!</p>
                </div>
            </a>
        </div>
    </div>

    <div class="c-dropdown dropdown u-mr-medium u-ml-small u-hidden-down@mobile">
        <a class="c-notification dropdown-toggle" href="#" id="dropdownMenuAlerts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="c-notification__icon">
                <i class="fa fa-bell-o"></i>
            </span>
            <span class="c-notification__number">3</span>
        </a>

        <div class="c-dropdown__menu c-dropdown__menu--large dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuAlerts">
            <a href="#" class="c-dropdown__item dropdown-item o-media">
                <span class="o-media__img u-mr-xsmall">
                    <span class="c-avatar c-avatar--xsmall">
                        <span class="c-avatar__img u-bg-success u-flex u-justify-center u-align-items-center">
                            <i class="fa fa-check u-text-large u-color-white"></i>
                        </span>
                    </span>

                </span>
                <div class="o-media__body">
                    <h6 class="u-mb-zero">Completed a task</h6>
                    <p class="u-text-mute">You have recieved a mention on twitter, check it out!</p>
                </div>
            </a>

            <a href="#" class="c-dropdown__item dropdown-item o-media">
                <span class="o-media__img u-mr-xsmall">
                    <span class="c-avatar c-avatar--xsmall">
                        <span class="c-avatar__img u-bg-fancy u-flex u-justify-center u-align-items-center">
                            <i class="fa fa-calendar u-text-large u-color-white"></i>
                        </span>
                    </span>

                </span>
                <div class="o-media__body">
                    <h6 class="u-mb-zero">Company meetup</h6>
                    <p class="u-text-mute">You have recieved a mention on twitter, check it out!</p>
                </div>
            </a>
            <a href="#" class="c-dropdown__item dropdown-item o-media">
                <span class="o-media__img u-mr-xsmall">
                    <span class="c-avatar c-avatar--xsmall">
                        <span class="c-avatar__img u-bg-primary u-flex u-justify-center u-align-items-center">
                            <i class="fa fa-info u-text-large u-color-white"></i>
                        </span>
                    </span>

                </span>
                <div class="o-media__body">
                    <h6 class="u-mb-zero">Someone mentioned you</h6>
                    <p class="u-text-mute">You have recieved a mention on twitter, check it out!</p>
                </div>
            </a>
        </div>
    </div>

    <div class="c-dropdown dropdown">
        <a  class="c-avatar c-avatar--xsmall has-dropdown dropdown-toggle" href="#" id="dropdwonMenuAvatar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="c-avatar__img" src="<%=current_admin_user.image%>" alt="User's Profile Picture">
        </a>
        <div class="c-dropdown__menu dropdown-menu dropdown-menu-right" aria-labelledby="dropdwonMenuAvatar">
            <a class="c-dropdown__item dropdown-item" href="#">Edit Profile</a>
            <a class="c-dropdown__item dropdown-item" href="#">View Activity</a>
            <%=link_to "Manage User", admin_users_path, :class=>"c-dropdown__item dropdown-item" %>
            <%=link_to "Setting", new_admin_setting_path, :class=>"c-dropdown__item dropdown-item" %>
            <%=link_to "Logout", destroy_admin_user_session_path, method: :delete, :class=>"c-dropdown__item dropdown-item"%>
        </div>
    </div>
</header>

app/views/shared/_left-side-bar.html.erb
<div class="o-page__sidebar js-page-sidebar">
    <div class="c-sidebar">
        <a class="c-sidebar__brand u-ml-medium" href="/">
            <img class="c-sidebar__brand-img" src="/logo.png" alt="Logo" > <%= Setting.site_name%>
        </a>

        <h4 class="c-sidebar__title">Dashboards</h4>
        <ul class="c-sidebar__list">
          <li class="c-sidebar__item">
            <%=link_to admin_dashboard_path, :class=> "c-sidebar__link is-active" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Overview
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_users_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Administrator
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_personalities_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Personality
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_services_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Service
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_experiences_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Experience
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_skills_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Skill
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_achivements_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Portfolio
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_blogs_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Blog
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_categories_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Category
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to new_admin_setting_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Setting
            <%end%>
          </li>

          <li class="c-sidebar__item">
            <%=link_to admin_visits_path, :class=> "c-sidebar__link" do%>
              <i class="fa fa-home u-mr-xsmall"></i>Activity
            <%end%>
          </li>

        </ul>

    </div><!-- // .c-sidebar -->
</div><!-- // .o-page__sidebar -->